; =====================================================
; DEFENSOR — game-defensor
; NodeMCU ESP8266 v2 + Fita WS2812B IP67 + 2x LDR
; Ambiente: VS Code + PlatformIO (Windows)
; =====================================================
[env:nodemcuv2]
platform    = espressif8266
board       = nodemcuv2
framework   = arduino
monitor_speed = 115200

lib_deps =
    fastled/FastLED          @ ^3.6.0
    knolleary/PubSubClient   @ ^2.8
    bblanchon/ArduinoJson    @ ^6.21.3
